version: '3.7'

services:
  web:
    image: nginx:stable
    container_name: web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/src/staticfiles
      - media:/src/media
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    depends_on:
      - url_shortener
    networks:
      - server

  url_shortener:
    image: url_shortener:latest
    container_name: url_shortener
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE:url_shortener.settings.prod
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/src/staticfiles
      - media:/src/media
    networks:
      - server
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    container_name: db
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shortener_user
      POSTGRES_PASSWORD: short!@#2nge43ener
      POSTGRES_DB: shortenerdb
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - server
    volumes:
      # - ./postgre/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      # - ./postgre/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - server_db:/var/lib/postgresql/data

networks:
  server:
    name: server
    driver: overlay
    attachable: true


volumes:
  staticfiles:
    name: staticfiles
    driver: local
  media:
    name: media
    driver: local
  server_db:
    name: server_db
    driver: local