version: '3.7'

services:
  web:
    image: nginx:stable
    container_name: web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/src/staticfiles
      - media:/src/media
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    depends_on:
      - url_shortener
    networks:
      - server

  url_shortener:
    image: url_shortener:latest
    container_name: url_shortener
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE:url_shortener.settings.prod
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/src/staticfiles
      - media:/src/media
    networks:
      - server

networks:
  server:
    name: server
    driver: overlay
    attachable: true


volumes:
  staticfiles:
    name: staticfiles
    driver: local
  media:
    name: media
    driver: local