# Generated by Django 4.1.3 on 2022-11-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('short_url', models.CharField(db_index=True, max_length=30, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('key', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
                'db_table': 'urls',
            },
        ),
    ]
