# Generated by Django 4.1.3 on 2022-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_url_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='redirect_url',
        ),
        migrations.AddField(
            model_name='url',
            name='url_key',
            field=models.CharField(db_index=True, default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='key',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='url',
            unique_together={('url_key', 'tag')},
        ),
    ]
