# Generated by Django 4.1.3 on 2022-11-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_url_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
