# Generated by Django 4.1.3 on 2022-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_url_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='url',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='url',
            name='key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='url',
            unique_together={('key', 'tag')},
        ),
    ]
